#!/usr/bin/bash

declare  -r input_file="${1:?input file is required!}"

cat "${input_file}" \
	| sed -E 's/ +\| +/\n/g' \
	| sed -E 's/^ +//' \
	| sed -E 's/^(sudo|nohup) +//'\
	| cut -d' ' -f1 \
	| sed -E 's#^.*/##' \
	| grep -E -v '^(echo|ll|vim|ls|cd|cat)$' \
	| awk '{total++; cmds[$1]++} END{for (cmd in cmds) { printf "%d %f %s\n", cmds[cmd], cmds[cmd]/total*100, cmd; }}' \
	| sort -t' ' -k1,1nr -k3,3 \
	| head -n10 \
	| awk '{printf "%4d %6.2f%% %s\n", $1, $2, $3;}'
